### ISSUE TITLE
OSError: Failed to fetch

### ISSUE THREAD

**Issue by shenxiangzhuang** [samuelcolvin/mkdocs-run-code#2]
I just try to click the run button in [https://docs.pydantic.dev/latest/](https://docs.pydantic.dev/latest/) and got the fellowing error after a few seconds. Is it because there are issues with my network?

```python
Error starting Python: PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 160, in _fetch_bytes
    return await fetch_bytes(self.url, fetch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_compat_in_pyodide.py", line 29, in fetch_bytes
    result_bytes = await (await pyfetch(url, **kwargs)).bytes()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/http.py", line 254, in pyfetch
    raise OSError(e.message) from None
OSError: Failed to fetch

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 355, in add_requirement
    await self.add_wheel(wheel, extras=set())
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 470, in add_wheel
    await wheel.download(self.fetch_kwargs)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 176, in download
    data = await self._fetch_bytes(fetch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 168, in _fetch_bytes
    raise ValueError(
ValueError: Can't fetch wheel from 'https://githubproxy.samuelcolvin.workers.dev/pydantic/pydantic-core/releases/download/v2.10.0/pydantic_core-2.10.0-cp311-cp311-emscripten_3_1_32_wasm32.whl'. One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS). Check if the server is sending the correct 'Access-Control-Allow-Origin' header.

```

**Comment by shenxiangzhuang** [comment]
It's the network problem
